-- שחזור אוטומטי מהמקור: כל פעולות "אייזנבלט הורים" (airtable_id rec0oPbDPinDlskeP)
-- מקור: supabase/seed.sql. מוחק את הקיימות לחבר זה ומכניס מחדש את כל 196 הפעולות.
-- להריץ ב-Supabase SQL Editor.

delete from transactions
where member_id = (select id from members where airtable_id = 'rec0oPbDPinDlskeP');

insert into transactions (member_id, amount, type, method, greg_date, heb_date, notes)
select m.id, t.amount, t.type, t.method, t.greg_date, t.heb_date, t.notes
from (values
  ('rec0oPbDPinDlskeP', 371::numeric, 'משיכה', null, null::date, 'ו אייר פג', 'ויטמינים רוזן'),
  ('rec0oPbDPinDlskeP', 588::numeric, 'משיכה', null, null::date, 'חשון פג', 'אימייל 2021'),
  ('rec0oPbDPinDlskeP', 1500::numeric, 'משיכה', null, null::date, 'כט טבת', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 22000::numeric, 'משיכה', null, null::date, 'כא אדר פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 740::numeric, 'משיכה', null, null::date, 'ט כסליו פה', 'הסעות להרשל'),
  ('rec0oPbDPinDlskeP', 100000::numeric, 'הפקדה', null, null::date, 'חשון פד', 'אשראי גולדיהרש לחזקי לב'),
  ('rec0oPbDPinDlskeP', 33000::numeric, 'משיכה', null, null::date, 'ו אדר פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 37000::numeric, 'משיכה', null, null::date, 'יט אדר פג', 'הלוואה לישראל'),
  ('rec0oPbDPinDlskeP', 14000::numeric, 'הפקדה', null, null::date, 'ד ניסן פו', 'העברה לפריזנט'),
  ('rec0oPbDPinDlskeP', 26000::numeric, 'משיכה', null, null::date, 'טבת פה', 'חתונה רוזנבלט'),
  ('rec0oPbDPinDlskeP', 36500::numeric, 'הפקדה', null, null::date, 'יא אדר פה', 'חוב טאטי מישראל לשיינפלד'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'כו אייר פא', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'הפקדה', null, null::date, 'ז אלול פה', 'מבוקשפן עו"ד'),
  ('rec0oPbDPinDlskeP', 40800::numeric, 'משיכה', null, null::date, 'יא חשון פה', 'לקארפ ירושה'),
  ('rec0oPbDPinDlskeP', 3060::numeric, 'משיכה', null, null::date, 'אלול פא', 'הודו אב'),
  ('rec0oPbDPinDlskeP', 400::numeric, 'משיכה', null, null::date, 'יד תמוז פג', 'נטע- חשבונות ירושה'),
  ('rec0oPbDPinDlskeP', 2070::numeric, 'משיכה', null, null::date, 'א אדא', 'משנ"י'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'הפקדה', null, null::date, '29.11.23', 'מחסדי רבקה'),
  ('rec0oPbDPinDlskeP', 1236::numeric, 'משיכה', null, null::date, 'ט ניסן פה', '0'),
  ('rec0oPbDPinDlskeP', 500::numeric, 'הפקדה', null, null::date, 'ה אייר פג', 'מאבי יפה'),
  ('rec0oPbDPinDlskeP', 0::numeric, 'משיכה', null, null::date, 'טז שבט פו', 'סיכום ירושה באבי'),
  ('rec0oPbDPinDlskeP', 100000::numeric, 'הפקדה', null, null::date, 'ט אלול', 'דולרים בבנק'),
  ('rec0oPbDPinDlskeP', 20930::numeric, 'משיכה', null, null::date, 'חשון פג', 'הודו אד"ב פב-תשרי פג'),
  ('rec0oPbDPinDlskeP', 4800::numeric, 'משיכה', null, null::date, 'שבט פו', 'לרותי לדירה'),
  ('rec0oPbDPinDlskeP', 1929::numeric, 'משיכה', null, null::date, 'יט כסליו פב', 'משנ"י חשון-כסליו'),
  ('rec0oPbDPinDlskeP', 700::numeric, 'הפקדה', null, null::date, 'ה תמוז פד', 'מזומן מעטפה'),
  ('rec0oPbDPinDlskeP', 1400000::numeric, 'הפקדה', null, null::date, 'ז שבט פו', 'תשלום דורלכר'),
  ('rec0oPbDPinDlskeP', 10000::numeric, 'הפקדה', null, null::date, 'א אדר פו', 'למוטי פריזנט'),
  ('rec0oPbDPinDlskeP', 6000::numeric, 'משיכה', null, null::date, 'ז שבט פו', 'העברה לחשבונם'),
  ('rec0oPbDPinDlskeP', 70000::numeric, 'הפקדה', null, null::date, 'ח אלול פה', 'לשיינפלד'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'הפקדה', null, null::date, 'כה אב פא', 'הפקדה'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'הפקדה', null, null::date, 'יא ניסן פו', 'העברה פרקש'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'משיכה', null, null::date, 'ב ניסן פד', 'מזומן למצות'),
  ('rec0oPbDPinDlskeP', 1600::numeric, 'משיכה', null, null::date, 'כט אד"א', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 605::numeric, 'משיכה', null, null::date, 'כח כסליו', 'לרוזן ויטמינים'),
  ('rec0oPbDPinDlskeP', 16000::numeric, 'הפקדה', null, null::date, 'יא כסליו פג', 'שקים'),
  ('rec0oPbDPinDlskeP', 150::numeric, 'משיכה', null, null::date, 'ד תשרי פד', 'הסעה לדיון הרשל'),
  ('rec0oPbDPinDlskeP', 1400::numeric, 'משיכה', null, null::date, 'כ כסליו פד', 'לרופא והסעה הרשל'),
  ('rec0oPbDPinDlskeP', 1350::numeric, 'משיכה', null, null::date, 'ח ניסן פה', 'למאפיה מצות'),
  ('rec0oPbDPinDlskeP', 618::numeric, 'משיכה', null, null::date, 'כ טבת פג', 'לפרידמן למזוזות'),
  ('rec0oPbDPinDlskeP', 13000::numeric, 'משיכה', null, null::date, 'יז שבט פג', 'הלוואה לישראל'),
  ('rec0oPbDPinDlskeP', 14700::numeric, 'הפקדה', null, null::date, 'א שבט פו', 'העברה'),
  ('rec0oPbDPinDlskeP', 10000::numeric, 'הפקדה', null, null::date, 'כו אדר פו', 'העברה לפריזנט'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'א סיון', 'פרסומת לסידור'),
  ('rec0oPbDPinDlskeP', 4000::numeric, 'משיכה', null, null::date, 'כט אב פה', '0'),
  ('rec0oPbDPinDlskeP', 80::numeric, 'משיכה', null, null::date, 'סיון פג', 'כריכות לסידורים באבי'),
  ('rec0oPbDPinDlskeP', 560::numeric, 'משיכה', null, null::date, 'ד אלול', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 4250::numeric, 'משיכה', null, null::date, 'א אב פד', 'לעו"ד שמעון מאיר'),
  ('rec0oPbDPinDlskeP', 122500::numeric, 'הפקדה', null, null::date, 'יב חשון פה', 'החזר מדירה ביתר'),
  ('rec0oPbDPinDlskeP', 2300::numeric, 'משיכה', null, null::date, 'כט אדר פג', 'לפאה יוכבד'),
  ('rec0oPbDPinDlskeP', 500::numeric, 'משיכה', null, null::date, 'כז ניסן', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 30000::numeric, 'משיכה', null, null::date, 'ה ניסן פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 230::numeric, 'משיכה', null, null::date, 'כב אייר', 'לישראל מצות'),
  ('rec0oPbDPinDlskeP', 348::numeric, 'משיכה', null, null::date, 'ל חשוון פב', 'לוויטמינים'),
  ('rec0oPbDPinDlskeP', 1512::numeric, 'הפקדה', null, null::date, 'ט אלול', 'דולרים בבנק'),
  ('rec0oPbDPinDlskeP', 100::numeric, 'משיכה', null, null::date, 'כד שבט פו', 'תרומה לשלומי'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'משיכה', null, null::date, 'יט תמוז פא', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 15740::numeric, 'משיכה', null, null::date, '0', 'הודו אייר פג-אדב פד'),
  ('rec0oPbDPinDlskeP', 1800::numeric, 'הפקדה', null, null::date, 'ו ניסן פו', 'למצות'),
  ('rec0oPbDPinDlskeP', 20400::numeric, 'משיכה', null, null::date, 'כד חשון פה', 'לגודלבסקי לירושה'),
  ('rec0oPbDPinDlskeP', 882::numeric, 'משיכה', null, null::date, 'מ07/23 עד סוף 24', 'קול הלשון להרשל'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'הפקדה', null, null::date, '45813', 'מרוזן שקים 1000 לחודש יגמור בהנ"ל'),
  ('rec0oPbDPinDlskeP', 1090::numeric, 'משיכה', null, null::date, 'כא אדר פו', 'לפרידמן'),
  ('rec0oPbDPinDlskeP', 11468::numeric, 'משיכה', null, null::date, '0', 'הודו ניסן- אלול פד'),
  ('rec0oPbDPinDlskeP', 525::numeric, 'משיכה', null, null::date, 'חשון פג', 'פאלפון 2021'),
  ('rec0oPbDPinDlskeP', 250::numeric, 'משיכה', null, null::date, 'ז ניסן פג', 'מחזורים דסי'),
  ('rec0oPbDPinDlskeP', 600::numeric, 'משיכה', null, null::date, 'כב אדא', 'העברה לסילבר'),
  ('rec0oPbDPinDlskeP', 110000::numeric, 'הפקדה', null, null::date, 'ז שבט פג', 'העברה לחשבוני מפרידמן'),
  ('rec0oPbDPinDlskeP', 441::numeric, 'משיכה', null, null::date, 'חשון פג', 'אימייל עד 09/22'),
  ('rec0oPbDPinDlskeP', 95000::numeric, 'משיכה', null, null::date, 'כסליו  פו', 'תיווך'),
  ('rec0oPbDPinDlskeP', 2444::numeric, 'משיכה', null, null::date, 'יט תמוז פא', 'משנת יוסף לחודשיים'),
  ('rec0oPbDPinDlskeP', 2860::numeric, 'משיכה', null, null::date, 'אב פא', 'הודו תמוז'),
  ('rec0oPbDPinDlskeP', 6500::numeric, 'הפקדה', null, null::date, 'ה אדר פה', 'מישראל'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'כט תמוז פד', 'העברה לעלי שיח'),
  ('rec0oPbDPinDlskeP', 700::numeric, 'משיכה', null, null::date, 'ו אלול פג', 'לרותי לחשבונות'),
  ('rec0oPbDPinDlskeP', 10000::numeric, 'הפקדה', null, null::date, 'אייר פא', 'קיבלתי מרוזנבלט'),
  ('rec0oPbDPinDlskeP', 200::numeric, 'משיכה', null, null::date, 'יג תשרי פו', 'לפרידמן'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'ניסן פד', 'העברה לחשבון הוצאות לוד'),
  ('rec0oPbDPinDlskeP', 2100::numeric, 'משיכה', null, null::date, 'אלול פב', 'פאה צירי'),
  ('rec0oPbDPinDlskeP', 2207::numeric, 'משיכה', null, null::date, 'י תמוז', 'הודו סיון'),
  ('rec0oPbDPinDlskeP', 110000::numeric, 'הפקדה', null, null::date, 'ב שבט פג', 'הפקדה בחשבוני מפרידמן'),
  ('rec0oPbDPinDlskeP', 3900::numeric, 'הפקדה', null, null::date, 'יא תשרי פב', 'שיקים ישראל אייר-כסליו פב'),
  ('rec0oPbDPinDlskeP', 30200::numeric, 'משיכה', null, null::date, 'טז שבט פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 3800::numeric, 'משיכה', null, null::date, 'כח אדר פו', 'לנגר'),
  ('rec0oPbDPinDlskeP', 3550::numeric, 'משיכה', null, null::date, 'ניסן פד', 'הוצאות מצות'),
  ('rec0oPbDPinDlskeP', 1700::numeric, 'משיכה', null, null::date, 'כג אדב', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 348::numeric, 'משיכה', null, null::date, 'י שבט פג', 'רוזן ויטמינים'),
  ('rec0oPbDPinDlskeP', 350::numeric, 'משיכה', null, null::date, 'כו ניסן פו', 'לכנס חינוך'),
  ('rec0oPbDPinDlskeP', 4475::numeric, 'משיכה', null, null::date, 'ו אדר פו', 'לשיינפלד חתונה'),
  ('rec0oPbDPinDlskeP', 17000::numeric, 'משיכה', null, null::date, 'ו אדר פו', 'לקרמיקה'),
  ('rec0oPbDPinDlskeP', 15000::numeric, 'הפקדה', null, null::date, 'טז שבט פו', 'בהעברה לפריזנט'),
  ('rec0oPbDPinDlskeP', 700::numeric, 'הפקדה', null, null::date, 'ד תמוז פד', 'מעטפה מזומן'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'אדר פה', 'עמלה כסף לאברהם שמואל'),
  ('rec0oPbDPinDlskeP', 4000::numeric, 'הפקדה', null, null::date, 'ז תמוז פא', 'שיק'),
  ('rec0oPbDPinDlskeP', 1800::numeric, 'משיכה', null, null::date, 'ניסן פג', 'פאה צירי'),
  ('rec0oPbDPinDlskeP', 600::numeric, 'הפקדה', null, null::date, 'כה טבת פד', 'מזומן'),
  ('rec0oPbDPinDlskeP', 6700::numeric, 'הפקדה', null, null::date, 'כ כסליו פג', 'הכניסו לי לפרידמן'),
  ('rec0oPbDPinDlskeP', 362::numeric, 'משיכה', null, null::date, 'ו אייר פג', 'לקול הדף'),
  ('rec0oPbDPinDlskeP', 400::numeric, 'משיכה', null, null::date, 'י כסליו פו', 'הסעות הרשל'),
  ('rec0oPbDPinDlskeP', 280::numeric, 'הפקדה', null, null::date, 'א שבט', 'מטופל טאטי'),
  ('rec0oPbDPinDlskeP', 22220::numeric, 'הפקדה', null, null::date, 'כט אלול פג', 'הפקדה להלוואה לשפרינגער'),
  ('rec0oPbDPinDlskeP', 66125::numeric, 'הפקדה', null, null::date, 'אייר פד', 'מגולדיהרש דרך אבי יפה'),
  ('rec0oPbDPinDlskeP', 3382::numeric, 'משיכה', null, null::date, 'חשון פב', 'הודו תשרי'),
  ('rec0oPbDPinDlskeP', 64::numeric, 'משיכה', null, null::date, 'ד תשרי פד', 'קניה תבלינים'),
  ('rec0oPbDPinDlskeP', 110::numeric, 'הפקדה', null, null::date, 'שבט פד', 'מכירת סידורים'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'משיכה', null, null::date, 'ט שבט פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 3000::numeric, 'משיכה', null, null::date, 'כח אדר פו', 'לריצוף'),
  ('rec0oPbDPinDlskeP', 9000::numeric, 'הפקדה', null, null::date, 'עד טבת פב', 'החזר חודשי מכהן'),
  ('rec0oPbDPinDlskeP', 41::numeric, 'משיכה', null, null::date, 'ל אדא פד', 'מונית להרשל'),
  ('rec0oPbDPinDlskeP', 1420::numeric, 'משיכה', null, null::date, 'יז אב פא', 'לרוזן-שפרינגער'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'יח אדא פד', 'ליעקב גודלבסקי-ירושה'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'ג אב', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 250000::numeric, 'הפקדה', null, null::date, 'אב פה', 'שקים הפקדתי לרוזנבלט'),
  ('rec0oPbDPinDlskeP', 100::numeric, 'משיכה', null, null::date, 'יב חשון פו', 'לצביקי'),
  ('rec0oPbDPinDlskeP', 300::numeric, 'משיכה', null, null::date, 'ח חשון פג', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 100000::numeric, 'הפקדה', null, null::date, 'סיון פד', 'העברה מאמריקה דרך אבי יפה'),
  ('rec0oPbDPinDlskeP', 8000::numeric, 'הפקדה', null, null::date, 'אייר פא', 'שיקים ישראל אייר-כסליו פב'),
  ('rec0oPbDPinDlskeP', 2118::numeric, 'משיכה', null, null::date, 'ד ניסן פו', 'לשיינפלד חתונה'),
  ('rec0oPbDPinDlskeP', 3965::numeric, 'משיכה', null, null::date, 'כט אב פא', 'לרוזן-שפרינגער'),
  ('rec0oPbDPinDlskeP', 348::numeric, 'משיכה', null, null::date, 'כד סיון', 'לרוזן ויטמינים'),
  ('rec0oPbDPinDlskeP', 150::numeric, 'משיכה', null, null::date, 'טו אב פה', 'להרשל'),
  ('rec0oPbDPinDlskeP', 6000::numeric, 'משיכה', null, null::date, 'ח תשרי פה', 'חתונה רוזנבלט'),
  ('rec0oPbDPinDlskeP', 3000::numeric, 'משיכה', null, null::date, 'כד טבת פו', 'לאשר ניסן'),
  ('rec0oPbDPinDlskeP', 53000::numeric, 'הפקדה', null, null::date, 'א כסליו פד', 'אשראי גולדיהרש לשיינפלד'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'משיכה', null, null::date, 'ל שבט פו', 'לנגר'),
  ('rec0oPbDPinDlskeP', 53710::numeric, 'הפקדה', null, null::date, '28.11.23', 'מחסדי רבקה'),
  ('rec0oPbDPinDlskeP', 500::numeric, 'משיכה', null, null::date, 'כט אייר פד', 'ליצחק שכטר'),
  ('rec0oPbDPinDlskeP', 432::numeric, 'משיכה', null, null::date, 'יא כסליו פג', 'ויטמינים רוזן'),
  ('rec0oPbDPinDlskeP', 645::numeric, 'משיכה', null, null::date, 'חשון פג', 'פאלפון 2022'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'יז טבת פו', 'דירה'),
  ('rec0oPbDPinDlskeP', 1030::numeric, 'משיכה', null, null::date, 'כו אדב פד', 'לקארפ'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'משיכה', null, null::date, 'יא אייר פד', 'לשרוליק'),
  ('rec0oPbDPinDlskeP', 30000::numeric, 'משיכה', null, null::date, 'יג סיון פד', 'לסוכן סידורים'),
  ('rec0oPbDPinDlskeP', 4000::numeric, 'הפקדה', null, null::date, 'ב אלול פא', 'שיק ומזומן'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'ו תשרי פב', 'העברה'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'משיכה', null, null::date, 'ג שבט פג', 'לעו"ד של הרשל'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'ט שבט פו', 'אלי לבניה'),
  ('rec0oPbDPinDlskeP', 240000::numeric, 'משיכה', null, null::date, 'כסליו פו', 'משיינפלד'),
  ('rec0oPbDPinDlskeP', 960::numeric, 'משיכה', null, null::date, 'ב תמוז', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 2700::numeric, 'משיכה', null, null::date, 'יא אייר פד', 'מחשבון גולדיהרש עבור רבינוביץ מביתר, צריך לחשב להוריד מהזכות של גולדיהרש'),
  ('rec0oPbDPinDlskeP', 1600::numeric, 'משיכה', null, null::date, 'כד טבת פו', 'לבנצי ורטהימר'),
  ('rec0oPbDPinDlskeP', 25000::numeric, 'משיכה', null, null::date, 'טז שבט פו', 'סיכום לוד'),
  ('rec0oPbDPinDlskeP', 83::numeric, 'משיכה', null, null::date, 'ג אב פא', 'לטלזטון'),
  ('rec0oPbDPinDlskeP', 800::numeric, 'משיכה', null, null::date, 'כד חשון פב', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 20000::numeric, 'משיכה', null, null::date, 'י אלול פד', 'הלוואה לשושן'),
  ('rec0oPbDPinDlskeP', 12294::numeric, 'משיכה', null, null::date, 'אייר פג', 'הודו חשון- ניסן פג'),
  ('rec0oPbDPinDlskeP', 1483::numeric, 'משיכה', null, null::date, 'א סיון פא', 'הודו אייר'),
  ('rec0oPbDPinDlskeP', 360::numeric, 'משיכה', null, null::date, 'טו חשון פו', 'לרוזנבלט בגדים'),
  ('rec0oPbDPinDlskeP', 400::numeric, 'משיכה', null, null::date, 'יז אדא', 'לשלזינגר'),
  ('rec0oPbDPinDlskeP', 600::numeric, 'משיכה', null, null::date, 'חורף פד', 'לרותי לחשבונות'),
  ('rec0oPbDPinDlskeP', 5000::numeric, 'הפקדה', null, null::date, 'כ שבט פו', 'אלי'),
  ('rec0oPbDPinDlskeP', 2137::numeric, 'משיכה', null, null::date, 'יא תשרי פב', 'סיכום משנת יוסף'),
  ('rec0oPbDPinDlskeP', 11000::numeric, 'הפקדה', null, null::date, 'כא אדר פו', 'העברה'),
  ('rec0oPbDPinDlskeP', 100::numeric, 'משיכה', null, null::date, 'יא אייר פה', 'לפרידמן חלאקה'),
  ('rec0oPbDPinDlskeP', 1800::numeric, 'משיכה', null, null::date, 'טז סיון פא', 'עוזרי'),
  ('rec0oPbDPinDlskeP', 3755::numeric, 'משיכה', null, null::date, 'טו אייר פא', 'משנת יוסף'),
  ('rec0oPbDPinDlskeP', 10000::numeric, 'משיכה', null, null::date, 'כח אדר פו', 'לנגר'),
  ('rec0oPbDPinDlskeP', 110000::numeric, 'הפקדה', null, null::date, 'סיון פא', 'מ10\06\21 1000 החזר לחודש'),
  ('rec0oPbDPinDlskeP', 250::numeric, 'משיכה', null, null::date, 'יח תמוז פד', 'בי"מ להרשל'),
  ('rec0oPbDPinDlskeP', 1100::numeric, 'משיכה', null, null::date, 'יז אייר פא', 'עוזרי'),
  ('rec0oPbDPinDlskeP', 30000::numeric, 'משיכה', null, null::date, 'אדר פה', 'לאברהם שמואל'),
  ('rec0oPbDPinDlskeP', 2000::numeric, 'הפקדה', null, null::date, 'כ כסליו פו', 'העברה'),
  ('rec0oPbDPinDlskeP', 4000::numeric, 'משיכה', null, null::date, 'כט אב פד', 'לרוזנבלט חתונה'),
  ('rec0oPbDPinDlskeP', 35000::numeric, 'משיכה', null, null::date, 'כד טבת פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 255::numeric, 'משיכה', null, null::date, 'כג אייר', 'לשפרינגער'),
  ('rec0oPbDPinDlskeP', 5100::numeric, 'משיכה', null, null::date, 'ל ניסן פד', 'לרוזנבלט לתנאים'),
  ('rec0oPbDPinDlskeP', 360::numeric, 'משיכה', null, null::date, 'כד תשרי פג', 'סידורים'),
  ('rec0oPbDPinDlskeP', 2600::numeric, 'משיכה', null, null::date, 'ט שבט פו', 'לבנצי ורטהימר'),
  ('rec0oPbDPinDlskeP', 80000::numeric, 'הפקדה', null, null::date, 'כ שבט פו', 'לאינגבר'),
  ('rec0oPbDPinDlskeP', 51500::numeric, 'משיכה', null, null::date, 'כה אב פד', 'לקארפ מירושה'),
  ('rec0oPbDPinDlskeP', 10530::numeric, 'משיכה', null, null::date, 'אייר פג', 'עו"ד לישראל'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'טז שבט פו', 'סיכום בונדס'),
  ('rec0oPbDPinDlskeP', 437::numeric, 'משיכה', null, null::date, 'ד ניסן פו', 'לפאלפון הרשל 2025'),
  ('rec0oPbDPinDlskeP', 34500::numeric, 'הפקדה', null, null::date, 'עדין לא קיבלתי שקים דחוים מרוזן לציין תאריך', 'החזרים מרוזן להלוואה'),
  ('rec0oPbDPinDlskeP', 250::numeric, 'הפקדה', null, null::date, 'יא תמוז פא', 'שיק'),
  ('rec0oPbDPinDlskeP', 1200::numeric, 'משיכה', null, null::date, 'יח שבט פד', 'לרופא והסעה הרשל'),
  ('rec0oPbDPinDlskeP', 1200::numeric, 'משיכה', null, null::date, 'כח אב פד', 'פאלפון והמבשר להרשל עד סוף 2024'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'משיכה', null, null::date, 'כח שבט', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 73000::numeric, 'משיכה', null, null::date, 'כסליו  פו', 'תיווך'),
  ('rec0oPbDPinDlskeP', 50000::numeric, 'משיכה', null, null::date, 'כ אדא פד', 'ליעקב גודלבסקי-ירושה'),
  ('rec0oPbDPinDlskeP', 26200::numeric, 'משיכה', null, null::date, 'כסליו  פו', 'עו"ד בוקשפן'),
  ('rec0oPbDPinDlskeP', 7000::numeric, 'משיכה', null, null::date, 'ו אייר פד', 'מחשבון גולדיהרש עבור רבינוביץ מביתר, צריך לחשב להוריד מהזכות של גולדיהרש'),
  ('rec0oPbDPinDlskeP', 1000::numeric, 'הפקדה', null, null::date, 'ה כסליו פד', 'שק להוצאות של הרשל'),
  ('rec0oPbDPinDlskeP', 30800::numeric, 'משיכה', null, null::date, 'ב שבט פו', 'לקבלן'),
  ('rec0oPbDPinDlskeP', 348::numeric, 'משיכה', null, null::date, 'ד תשרי פג', 'ויטמינים רוזן'),
  ('rec0oPbDPinDlskeP', 8650::numeric, 'משיכה', null, null::date, 'יב אייר פד', 'רוזנבלט הוצאות חתונה'),
  ('rec0oPbDPinDlskeP', 3915::numeric, 'משיכה', null, null::date, 'תשרי פב', 'הודו אלול'),
  ('rec0oPbDPinDlskeP', 65::numeric, 'משיכה', null, null::date, 'יג אלול פד', 'קיטל'),
  ('rec0oPbDPinDlskeP', 3000::numeric, 'משיכה', null, null::date, 'כד טבת פו', 'לרותי לדירה'),
  ('rec0oPbDPinDlskeP', 1150::numeric, 'משיכה', null, null::date, 'יח אב פא', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 100::numeric, 'משיכה', null, null::date, 'יט אלול פד', 'הסעה הרשל לשרייכר'),
  ('rec0oPbDPinDlskeP', 3339::numeric, 'הפקדה', null, null::date, 'יד אייר פא', 'סיכום'),
  ('rec0oPbDPinDlskeP', 18300::numeric, 'משיכה', null, null::date, 'ניסן פד', '5000$ של האייער העברתי למקבלים מכיסי'),
  ('rec0oPbDPinDlskeP', 600::numeric, 'משיכה', null, null::date, 'כה תשרי פב', 'לעוזרי'),
  ('rec0oPbDPinDlskeP', 15000::numeric, 'משיכה', null, null::date, 'כו חשון פה', 'לרוזנבלט חתונה'),
  ('rec0oPbDPinDlskeP', 645::numeric, 'משיכה', null, null::date, 'ב אייר פג', 'ישראל לגרושה')
) as t(member_aid, amount, type, method, greg_date, heb_date, notes)
join members m on m.airtable_id = t.member_aid;
